### ISSUE TITLE
Server counters

### ISSUE THREAD

**Issue by Nirlep5252** [Nirlep5252/EpicBot#49]
Server counters on voice channels/text channels

(opening this by myself so I don't forget)

**Comment by Nirlep5252** [comment]
ignore

**Comment by ahnaf-zamil** [comment]
Implementation will be messy, although possible. Editing voice channel names very frequently hit API rate limits. As far as I am concerned, editing the name of 5 channels within a short time puts you on a 300-second cooldown.

Having a `discord.ext.task` for this would also be a disaster because you might have a thousand servers that need their stats changed. So changing all that in a single task will be a pain.

The best thing (according to my opinion) would be to ensure that the bot **always retries** the request after being rate limited.

**Comment by Nirlep5252** [comment]
Hm yes that's a bit of problem.

**Comment by Nirlep5252** [comment]
I do have a couple of ideas:

- Maybe I change the count after a few percentage of members increase, so if a server has 100 members the next update will be at 105 and if it has 1,000 members it updates at 1,050 which won't update that quick and will definitely won't ratelimit the bot, but the downside of that is that it won't be live count/statistics so users might not like it.
- Or what I can do is have an asyncio.sleep() after member count update but the sleep depends on the guild member count so If the bot just updated a big server's count, it will sleep for a bit cuz they have members growing really fast, but that would slow down counts for other servers because of a big server so idk about this one too

If you have some suggestions I'd highly appreciate them :D
