### ISSUE TITLE
VoteReminder Command

### ISSUE THREAD

**Issue by Maaaalik** [Nirlep5252/EpicBot#80]
If you vote you will also get the "Thank you" message, but if you don't vote after 12 hours you won't get the "Vote Reminder" message. Voting reminder is also enabled, but the message is not sent.

The "Votes" command also shows how long it was when you last voted.

**Comment by Nirlep5252** [comment]
The vote reminder [code](https://github.com/Nirlep5252/EpicBot/blob/main/cogs_hidden/vote_tracking.py#L202-L226) was commented out because caching was removed. 

You can revert [this commit](https://github.com/Nirlep5252/EpicBot/commit/3b8d2850433ab20834fb442174804ac8484f5323) if you want the vote reminder feature.
